name: Pre Release Checks
on:
  workflow_dispatch:
  push:
    branches:
      - release-please--branches--main
  pull_request:
    branches:
      - release-please--branches--main

jobs:
  check-version-alignment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run make check-version-alignment
        run: make check-version-alignment